"""Initial database schema

Revision ID: 0fd138ff09d4
Revises: 61b1dae3fa62
Create Date: 2025-06-26 10:10:21.580888

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0fd138ff09d4"
down_revision: Union[str, Sequence[str], None] = "61b1dae3fa62"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "linguistapplications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "approved", "rejected", name="application_status_enum"),
            nullable=False,
        ),
        sa.Column("id_document_url", sa.String(), nullable=False),
        sa.Column("cv_document_url", sa.String(), nullable=False),
        sa.Column("certifications_document_url", sa.String(), nullable=True),
        sa.Column("research_papers_document_url", sa.String(), nullable=True),
        sa.Column(
            "submitted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("linguistapplications")
    # ### end Alembic commands ###
