"""learning path model v2

Revision ID: 23957d2010e2
Revises: f694125bd853
Create Date: 2025-09-20 11:21:57.156664

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "23957d2010e2"
down_revision: Union[str, Sequence[str], None] = "f694125bd853"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "learningpaths",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("path_name", sa.String(length=100), nullable=False),
        sa.Column("language_name", sa.String(length=50), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "path_name", "language_name", name="_user_path_language_uc"
        ),
    )
    op.create_table(
        "learningpathglossarys",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("glossary_name", sa.String(length=100), nullable=False),
        sa.Column("learning_path_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["learning_path_id"], ["learningpaths.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("learningpathglossarys")
    op.drop_table("learningpaths")
    # ### end Alembic commands ###
