"""learning path model v5

Revision ID: 43348823f98b
Revises: ead6a3b65cd2
Create Date: 2025-09-21 12:27:26.956890

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "43348823f98b"
down_revision: Union[str, Sequence[str], None] = "ead6a3b65cd2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "userglossaryprogresss",
        sa.Column(
            "retry_pile_ids", sa.ARRAY(sa.UUID()), server_default="{}", nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("userglossaryprogresss", "retry_pile_ids")
    # ### end Alembic commands ###
