"""Adjusted linguist application

Revision ID: 4942f1396707
Revises: c4fed89bf6d6
Create Date: 2025-08-08 13:14:51.046503

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4942f1396707"
down_revision: Union[str, Sequence[str], None] = "c4fed89bf6d6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "linguistapplications",
        sa.Column("google_scholar_url", sa.String(), nullable=False),
    )
    op.add_column(
        "linguistapplications",
        sa.Column(
            "research_papers_gcs_keys", postgresql.ARRAY(sa.String()), nullable=False
        ),
    )
    op.drop_column("linguistapplications", "certifications_document_url")
    op.drop_column("linguistapplications", "research_papers_document_url")
    op.drop_column("linguistapplications", "cv_document_url")
    op.drop_column("linguistapplications", "id_document_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "linguistapplications",
        sa.Column("id_document_url", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "linguistapplications",
        sa.Column("cv_document_url", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "linguistapplications",
        sa.Column(
            "research_papers_document_url",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "linguistapplications",
        sa.Column(
            "certifications_document_url",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("linguistapplications", "research_papers_gcs_keys")
    op.drop_column("linguistapplications", "google_scholar_url")
    # ### end Alembic commands ###
