"""updated term model

Revision ID: 56b5324f51ae
Revises: 4c65895950ce
Create Date: 2025-08-19 11:46:53.957565

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = "56b5324f51ae"
down_revision: Union[str, Sequence[str], None] = "4c65895950ce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("term_translations_translation_id_fkey"),
        "term_translations",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("term_translations_term_id_fkey"), "term_translations", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "term_translations",
        "terms",
        ["translation_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None, "term_translations", "terms", ["term_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "term_translations", type_="foreignkey")
    op.drop_constraint(None, "term_translations", type_="foreignkey")
    op.create_foreign_key(
        op.f("term_translations_term_id_fkey"),
        "term_translations",
        "terms",
        ["term_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("term_translations_translation_id_fkey"),
        "term_translations",
        "terms",
        ["translation_id"],
        ["id"],
    )
    # ### end Alembic commands ###
