"""Added Feedback

Revision ID: 7b8f12d56ab0
Revises: 2808795c2e8b
Create Date: 2025-08-20 06:44:08.597278

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7b8f12d56ab0"
down_revision: Union[str, Sequence[str], None] = "2808795c2e8b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "termapplications", "term_id", existing_type=sa.UUID(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "termapplications", "term_id", existing_type=sa.UUID(), nullable=False
    )
    # ### end Alembic commands ###
