"""Added term applications

Revision ID: b337fa999e63
Revises: 8c929b111572
Create Date: 2025-08-17 14:45:00.614176

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b337fa999e63"
down_revision: Union[str, Sequence[str], None] = "8c929b111572"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "termapplications", sa.Column("review", sa.String(length=2000), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("termapplications", "review")
    # ### end Alembic commands ###
