"""term-application update

Revision ID: bd4e1862768f
Revises: 7b8f12d56ab0
Create Date: 2025-09-19 06:16:41.015687

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = "bd4e1862768f"
down_revision: Union[str, Sequence[str], None] = "7b8f12d56ab0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("termapplications_term_id_fkey"), "termapplications", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("termapplications_is_edit_for_term_id_fkey"),
        "termapplications",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "termapplications",
        "terms",
        ["is_edit_for_term_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None, "termapplications", "terms", ["term_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "termapplications", type_="foreignkey")
    op.drop_constraint(None, "termapplications", type_="foreignkey")
    op.create_foreign_key(
        op.f("termapplications_is_edit_for_term_id_fkey"),
        "termapplications",
        "terms",
        ["is_edit_for_term_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("termapplications_term_id_fkey"),
        "termapplications",
        "terms",
        ["term_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###
