"""add feedback priority column

Revision ID: de172491dbc4
Revises: 59116ba32391
Create Date: 2025-09-28 09:40:27.816439

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "de172491dbc4"
down_revision: Union[str, Sequence[str], None] = "59116ba32391"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    feedback_priority_enum = sa.Enum(
        "low", "medium", "high", "critical", name="feedback_priority_enum"
    )
    feedback_priority_enum.create(op.get_bind())

    # Add the column with the enum type
    op.add_column(
        "feedbacks",
        sa.Column(
            "priority", feedback_priority_enum, nullable=False, server_default="medium"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("feedbacks", "priority")

    # Drop the enum type
    feedback_priority_enum = sa.Enum(
        "low", "medium", "high", "critical", name="feedback_priority_enum"
    )
    feedback_priority_enum.drop(op.get_bind())
    # ### end Alembic commands ###
