"""learning path model v4

Revision ID: ead6a3b65cd2
Revises: eb523d80b3b0
Create Date: 2025-09-21 11:50:53.409657

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ead6a3b65cd2"
down_revision: Union[str, Sequence[str], None] = "eb523d80b3b0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "userglossaryprogresss",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("language_name", sa.String(length=50), nullable=False),
        sa.Column("glossary_name", sa.String(length=100), nullable=False),
        sa.Column("last_card_index", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "language_name", "glossary_name", name="_user_lang_glossary_uc"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("userglossaryprogresss")
    # ### end Alembic commands ###
