"""learning path model v3

Revision ID: eb523d80b3b0
Revises: 23957d2010e2
Create Date: 2025-09-20 12:30:51.125951

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = "eb523d80b3b0"
down_revision: Union[str, Sequence[str], None] = "23957d2010e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("_user_path_language_uc"), "learningpaths", type_="unique")
    op.create_unique_constraint(
        "_user_path_name_uc", "learningpaths", ["user_id", "path_name"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("_user_path_name_uc", "learningpaths", type_="unique")
    op.create_unique_constraint(
        op.f("_user_path_language_uc"),
        "learningpaths",
        ["user_id", "path_name", "language_name"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
