"""Adjusted linguist application

Revision ID: f01636d83e8d
Revises: 4942f1396707
Create Date: 2025-08-12 19:35:45.342941

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = "f01636d83e8d"
down_revision: Union[str, Sequence[str], None] = "4942f1396707"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("linguistapplications_user_id_key"), "linguistapplications", type_="unique"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("linguistapplications_user_id_key"),
        "linguistapplications",
        ["user_id"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
