"""add user preferences table

Revision ID: fbe53acc59ce
Revises: de172491dbc4
Create Date: 2025-09-28 07:36:36.653789

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fbe53acc59ce"
down_revision: Union[str, Sequence[str], None] = "de172491dbc4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_preferences",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("dark_mode", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column(
            "offline_mode_enabled", sa.Boolean(), nullable=False, server_default="false"
        ),
        sa.Column(
            "ui_language", sa.String(length=3), nullable=False, server_default="'eng'"
        ),
        sa.Column("text_size", sa.Integer(), nullable=False, server_default="16"),
        sa.Column("text_spacing", sa.Float(), nullable=False, server_default="1.0"),
        sa.Column(
            "high_contrast_mode", sa.Boolean(), nullable=False, server_default="false"
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_index(
        op.f("ix_user_preferences_user_id"),
        "user_preferences",
        ["user_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_preferences_user_id"), table_name="user_preferences")
    op.drop_table("user_preferences")
    # ### end Alembic commands ###
