# CORRECTED linguist-application-service/Dockerfile
FROM python:3.11-slim

# Set the standard working directory to /app
WORKDIR /app

COPY ./linguist-application-service/requirements.txt /app/requirements.txt