name: Deploy Backend Services

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'backend/auth-service/**'
      - 'backend/analytics-service/**'
      - 'backend/glossary-service/**'
      - 'backend/linguist-application-service/**'
      - 'backend/search-service/**'
      - 'backend/vote-service/**'
      - 'backend/comment-service/**'

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: us-central1
  GAR_LOCATION: us-central1-docker.pkg.dev
  GAR_REPOSITORY: mavito-images

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.DSFSI_SA_KEY }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Docker auth
        run: |
          echo '${{ secrets.DSFSI_SA_KEY }}' > sa-key.json
          gcloud auth activate-service-account --key-file=sa-key.json
          gcloud auth configure-docker $GAR_LOCATION --quiet
          rm sa-key.json

      - name: Build and push images
        run: |
          SERVICES=(
            "analytics-service"
            "auth-service"
            "glossary-service"
            "linguist-application-service"
            "search-service"
            "vote-service"
            "comment-service"
          )

          for SERVICE in "${SERVICES[@]}"; do
            IMAGE="$GAR_LOCATION/$GCP_PROJECT_ID/$GAR_REPOSITORY/$SERVICE:latest"
            docker build -t "$IMAGE" -f "backend/$SERVICE/Dockerfile" backend
            docker push "$IMAGE"
          done

      - name: Deploy services to Cloud Run
        run: |
          SERVICES=(
            "analytics-service"
            "auth-service"
            "glossary-service"
            "linguist-application-service"
            "search-service"
            "vote-service"
            "comment-service"
          )

          for SERVICE in "${SERVICES[@]}"; do
            IMAGE="$GAR_LOCATION/$GCP_PROJECT_ID/$GAR_REPOSITORY/$SERVICE:latest"
            gcloud run deploy "$SERVICE" \
              --image="$IMAGE" \
              --region="$GCP_REGION" \
              --project="$GCP_PROJECT_ID" \
              --platform=managed \
              --allow-unauthenticated \
              --quiet \
              --set-env-vars="SECRET_KEY=${{ secrets.SECRET_KEY }},DB_USER=${{ secrets.DB_USER }},DB_NAME=${{ secrets.DB_NAME }},DB_PASSWORD=${{ secrets.DB_PASSWORD }},INSTANCE_CONNECTION_NAME=${{ secrets.INSTANCE_CONNECTION_NAME }},GCS_BUCKET_NAME=marito_bucket,BACKEND_CORS_ORIGINS=${{ secrets.BACKEND_CORS_ORIGINS }},ALGORITHM=HS256,GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}"
          done
