name: Run Database Migrations

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'backend/migrations/**'
      - 'backend/alembic-service/**'

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: us-central1
  GAR_LOCATION: us-central1-docker.pkg.dev
  GAR_REPOSITORY: mavito-images

jobs:
  deploy-migrations:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.DSFSI_SA_KEY }}
          # Remove token_format to avoid token creation

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Docker auth (using JSON key directly)
        run: |
          echo ${{ secrets.DSFSI_SA_KEY }} > sa-key.json
          gcloud auth activate-service-account --key-file=sa-key.json
          gcloud auth configure-docker $GAR_LOCATION --quiet
          rm sa-key.json

      - name: Build and push image
        run: |
          docker build \
            -t $GAR_LOCATION/$GCP_PROJECT_ID/$GAR_REPOSITORY/alembic-service:latest \
            -f backend/alembic-service/Dockerfile \
            backend
          docker push $GAR_LOCATION/$GCP_PROJECT_ID/$GAR_REPOSITORY/alembic-service:latest

      - name: Deploy and run migrations
        run: |
          gcloud run jobs deploy alembic-migrations \
            --image=$GAR_LOCATION/$GCP_PROJECT_ID/$GAR_REPOSITORY/alembic-service:latest \
            --set-env-vars="DB_URL=postgresql+asyncpg://${{ secrets.DB_USER }}:$(python3 -c "import urllib.parse; print(urllib.parse.quote('${{ secrets.DB_PASSWORD }}'))")@/${{ secrets.DB_NAME }}?host=/cloudsql/${{ secrets.INSTANCE_CONNECTION_NAME }}" \
            --set-cloudsql-instances=${{ secrets.INSTANCE_CONNECTION_NAME }} \
            --region=$GCP_REGION \
            --project=$GCP_PROJECT_ID \
            --command="alembic upgrade head" \
            --quiet
          gcloud run jobs execute alembic-migrations \
            --region=$GCP_REGION \
            --project=$GCP_PROJECT_ID \
            --wait
