name: Run Database Migrations

on:
  workflow_dispatch:  # Allows manual triggering
  push:
    branches: [main]
    paths: ['backend/migrations/**']

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: us-central1
  GAR_LOCATION: us-central1-docker.pkg.dev

jobs:
  deploy-migrations:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'  # Required for Workload Identity

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.DSFSI_SA_KEY }}  # Use service account key
          # OR use Workload Identity (choose one):
          # workload_identity_provider: projects/${{ secrets.GCP_PROJECT_ID }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          # service_account: my-backend-service@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1

      - name: Deploy and run migrations
        run: |-
          gcloud run jobs update alembic-migrations \
            --project=$GCP_PROJECT_ID \
            --region=$GCP_REGION \
            --image=us-central1-docker.pkg.dev/$GCP_PROJECT_ID/mavito-images/alembic-service:latest \
            --update-env-vars="DB_URL=postgresql+asyncpg://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@/${{ secrets.DB_NAME }}?host=/cloudsql/${{ secrets.INSTANCE_CONNECTION_NAME }}" \
            --args="alembic upgrade head"

          gcloud run jobs execute alembic-migrations \
            --project=$GCP_PROJECT_ID \
            --region=$GCP_REGION \
            --wait
