name: Run Database Migrations

on:
  push:
    branches:
      - main
    paths:
      - 'backend/migrations/alembic/versions/**'

jobs:
  deploy-migration-job:
    name: Deploy and Run Migration Job
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.DSFSI_SA_KEY }}
          workload_identity_provider: 'projects/${{ secrets.GCP_PROJECT_ID }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'my-backend-service@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Deploy Cloud Run Job
        run: |
          # Replace with your actual Cloud Run job configuration
          gcloud run jobs replace jobs/alembic-migrations.yaml \
            --project=${{ secrets.GCP_PROJECT_ID }} \
            --region=${{ secrets.GCP_REGION }}

      - name: Execute Migration Job
        run: |
          gcloud run jobs execute alembic-migrations \
            --project=${{ secrets.GCP_PROJECT_ID }} \
            --region=${{ secrets.GCP_REGION }} \
            --wait
